// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQFwJnB1ftz-n9ixipkhO6M09TSBuKWwc',
    appId: '1:976845575777:web:bbcd5d12a138ac3e807c20',
    messagingSenderId: '976845575777',
    projectId: 'sec-e-comm',
    authDomain: 'sec-e-comm.firebaseapp.com',
    storageBucket: 'sec-e-comm.firebasestorage.app',
    measurementId: 'G-T4PLYTQMQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlkxZ601jZorZ_8AWfAGTxDJU7a5N4YsI',
    appId: '1:976845575777:android:de055d0d80b0ecaf807c20',
    messagingSenderId: '976845575777',
    projectId: 'sec-e-comm',
    storageBucket: 'sec-e-comm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD9FE0waB6hNpeKCtbtWlOabTNjqiJcIk',
    appId: '1:976845575777:ios:186b2cc0b40bf4e2807c20',
    messagingSenderId: '976845575777',
    projectId: 'sec-e-comm',
    storageBucket: 'sec-e-comm.firebasestorage.app',
    iosBundleId: 'io.wheezedev.sececommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD9FE0waB6hNpeKCtbtWlOabTNjqiJcIk',
    appId: '1:976845575777:ios:186b2cc0b40bf4e2807c20',
    messagingSenderId: '976845575777',
    projectId: 'sec-e-comm',
    storageBucket: 'sec-e-comm.firebasestorage.app',
    iosBundleId: 'io.wheezedev.sececommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQFwJnB1ftz-n9ixipkhO6M09TSBuKWwc',
    appId: '1:976845575777:web:ed589f45cd15888c807c20',
    messagingSenderId: '976845575777',
    projectId: 'sec-e-comm',
    authDomain: 'sec-e-comm.firebaseapp.com',
    storageBucket: 'sec-e-comm.firebasestorage.app',
    measurementId: 'G-SJWPZH07N3',
  );
}
